site_name: aws-app-1
site_description: just a test app

nav:
  - Introduction: index.md
  - 'Application architecture': architecture.md
  - 'Deploy application': deploy.md
  - 'How to use application': usage.md

plugins:
  - techdocs-core